<#
.SYNOPSIS
    Generates an interactive HTML report of users with custom security attributes in Microsoft Entra ID.
    Connect first with Connect-RKGraph; this cmdlet uses the existing connection.
.DESCRIPTION
    Connects to Microsoft Graph API and retrieves all users with specified custom security attributes.
    Supports dynamic attribute set selection, filtering, and sending reports via email.
    The report includes filterable tables with export capabilities (Excel, CSV, PDF, Print).
.PARAMETER AttributeSet
    The custom security attribute set to query. Defaults to "CustomerData".
.PARAMETER AttributeNames
    Specific attribute names to include. If not specified, all attributes in the set are used.
.PARAMETER Filters
    Hashtable of attribute name/value pairs to filter users. Example: @{ CustomerName = "Contoso" }
.PARAMETER SendEmail
    Send the report as an email attachment via Microsoft Graph Mail.Send.
.PARAMETER Recipient
    Email addresses to send the report to. Required when -SendEmail is used.
.PARAMETER From
    Sender email address. If omitted, sends as the currently authenticated user.
.PARAMETER ExportPath
    Full path for the HTML report file. Defaults to current directory.
.PARAMETER DebugMode
    Enable verbose debug output.
.EXAMPLE
    Get-CustomSecurityAttributesReport
    Generate report with default CustomerData attribute set.
.EXAMPLE
    Get-CustomSecurityAttributesReport -AttributeSet "Engineering" -AttributeNames "Project","CostCenter"
    Query specific attribute set with custom attributes.
.EXAMPLE
    Get-CustomSecurityAttributesReport -SendEmail -Recipient "admin@contoso.com"
    Generate report and email it.
#>
function Get-CustomSecurityAttributesReport {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory = $false)]
        [string]$AttributeSet = "CustomerData",

        [Parameter(Mandatory = $false)]
        [string[]]$AttributeNames,

        [Parameter(Mandatory = $false)]
        [hashtable]$Filters,

        [Parameter(Mandatory = $false)]
        [switch]$SendEmail,

        [Parameter(Mandatory = $false)]
        [string[]]$Recipient,

        [Parameter(Mandatory = $false)]
        [string]$From,

        [Parameter(Mandatory = $false)]
        [string]$ExportPath,

        [Parameter(Mandatory = $false)]
        [switch]$DebugMode
    )

    $ErrorActionPreference = 'Stop'
    try {
        $ctx = Get-MgContext -ErrorAction SilentlyContinue
        if (-not $ctx) { throw 'Not connected to Microsoft Graph. Run Connect-RKGraph first.' }

        # Get tenant information
        $tenantInfo = Invoke-MgGraphRequest -Uri 'v1.0/organization' -Method Get -OutputType PSObject
        $tenantName = $tenantInfo.value[0].displayName

        # Fetch attribute data
        $reportData = Get-CustomSecurityAttributeData -AttributeSet $AttributeSet -AttributeNames $AttributeNames -Filters $Filters -DebugMode:$DebugMode

        if ($reportData.UserData.Count -eq 0) {
            Write-Host 'No users found matching the criteria.' -ForegroundColor Yellow
            return
        }

        Write-Host "Found $($reportData.UserData.Count) user(s) with custom security attributes." -ForegroundColor Green

        # Generate HTML report
        $htmlPath = New-CustomSecurityAttributesHTMLReport -TenantName $tenantName -UserData $reportData.UserData -AttributeSet $AttributeSet -AttributeNames $reportData.AttributeNames -ExportPath $ExportPath

        # Send email if requested
        if ($SendEmail -and $Recipient) {
            $subject = "$tenantName - Custom Security Attributes Report"
            $bodyHtml = @"
<html><body style="font-family: 'Source Serif 4', Georgia, serif;">
<h2>Custom Security Attributes Report</h2>
<p>Attached is the latest Custom Security Attributes report for <strong>$tenantName</strong>.</p>
<p>Open the attached HTML in a browser for the interactive dashboard.</p>
<p style='color:#787468;'>Generated by RKSolutions - please do not reply.</p>
</body></html>
"@
            $emailSent = Send-EmailWithAttachment -Recipient $Recipient -AttachmentPath $htmlPath -From $From -Subject $subject -BodyHtml $bodyHtml
            if ($emailSent) { Write-Host 'INFO: Email sent successfully.' -ForegroundColor Green } else { Write-Host 'ERROR: Failed to send email.' -ForegroundColor Red }
        }

        if ($SendEmail -and (Test-Path -Path $htmlPath)) {
            Remove-Item -Path $htmlPath -Force
            Write-Host 'INFO: Temporary report file deleted.' -ForegroundColor Green
        }
    }
    catch { Write-Error "Error: $_"; throw $_ }
}
